[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "24"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://www.dionisweb.com/*"
  to = "https://dionisweb.com/:splat"
  status = 301
  force = true
