import test from 'node:test';
import assert from 'node:assert/strict';
import {getPaymentOption,resolvePaymentAmount,paymentOptionsForClient} from '../netlify/functions/paypal-shared.mjs';
import createOrder from '../netlify/functions/paypal-create-order.mjs';
import {isMatchingCapture} from '../netlify/functions/paypal-capture-order.mjs';
test('custom minimum, decimal precision and strict server validation',()=>{const o=getPaymentOption('custom-project');for(const [raw,expected]of [['1','1.00'],['1.2','1.20'],['1.01','1.01'],['200','200.00'],['999999.99','999999.99']])assert.equal(resolvePaymentAmount(o,raw),expected);for(const raw of [undefined,null,1,'0','0.99','-1','1e3','1.001','NaN','Infinity','1000000','1,00',' 1',''])assert.throws(()=>resolvePaymentAmount(o,raw));assert.equal(paymentOptionsForClient().find(x=>x.id===o.id).customAmount,true);});
test('fixed packages cannot be discounted by client supplied amount',()=>{assert.equal(resolvePaymentAmount(getPaymentOption('landing-page'),'1'),'40.00');assert.equal(resolvePaymentAmount(getPaymentOption('business-website'),'1'),'100.00');});
test('invalid custom amounts are rejected before PayPal access',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('PayPal must not be called');};try{for(const amount of ['0.50','1.001','1e2']){const r=await createOrder(new Request('https://dionisweb.com/api/paypal/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packageId:'custom-project',amount,customer:{firstName:'Test',lastName:'Client',email:'test@example.invalid',phone:'+1234567890'}})}));assert.equal(r.status,400);}}finally{globalThis.fetch=original;}});
test('capture confirmation requires completed matching currency and amount',()=>{const p={amount:'1.00',currency:'USD'};const payload={status:'COMPLETED',purchase_units:[{payments:{captures:[{status:'COMPLETED',amount:{value:'1.00',currency_code:'USD'}}]}}]};assert.equal(isMatchingCapture(payload,p),true);for(const changed of [{...p,amount:'200.00'},{...p,currency:'EUR'}])assert.equal(isMatchingCapture(payload,changed),false);assert.equal(isMatchingCapture({...payload,status:'APPROVED'},p),false);const pending=structuredClone(payload);pending.purchase_units[0].payments.captures[0].status='PENDING';assert.equal(isMatchingCapture(pending,p),false);});

import {createWalletHandler} from '../netlify/functions/paypal-wallets.mjs';
test('wallet eligibility uses the PayPal response and does not invent domain verification',async()=>{const handler=createWalletHandler({token:async()=>'test-token',fetch:async(url,init)=>{assert.ok(url.endsWith('/v2/payments/find-eligible-methods'));const body=JSON.parse(init.body);assert.equal(body.purchase_units[0].amount.value,'1.00');return Response.json({eligible_methods:{google_pay:{},apple_pay:{}}});}});const r=await handler(new Request('https://dionisweb.com/api/paypal/wallets'));assert.equal(r.status,200);const data=await r.json();assert.equal(data.googlePayEligible,true);assert.equal(data.applePayEligible,true);assert.equal(data.appleDomainVerified,false);assert.ok(!JSON.stringify(data).includes('test-token'));});
test('ineligible wallet methods stay unavailable and provider failures fail closed',async()=>{const token=async()=>'test-token';let handler=createWalletHandler({token,fetch:async()=>Response.json({eligible_methods:{}})});let data=await(await handler(new Request('https://dionisweb.com/api/paypal/wallets'))).json();assert.equal(data.googlePayEligible,false);assert.equal(data.applePayEligible,false);handler=createWalletHandler({token,fetch:async()=>Response.json({message:'Provider denied'},{status:403})});const r=await handler(new Request('https://dionisweb.com/api/paypal/wallets'));assert.equal(r.status,502);data=await r.json();assert.equal(data.available,false);assert.ok(!JSON.stringify(data).includes('Provider denied'));});
