'use client';
import { useEffect, useState } from 'react';
type Report={installedAt:string|null;days:number;pageviews:number;dailyUniqueSum:number;daily:{day:string;pageviews:number;unique:number}[];pages:Record<string,number>;sources:Record<string,number>;devices:Record<string,number>;events:Record<string,number>};
export function AnalyticsPanel(){const [days,setDays]=useState('7'),[data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;fetch(`/api/admin?action=analytics&days=${days}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[days,refresh]);
 const labels:Record<string,string>={whatsapp_click:'Clicuri WhatsApp',contact_click:'Clicuri contact',checkout_start:'Inițieri checkout',pageview:'Vizualizări'};
 return <section className="admin-card"><h2>Statistici de trafic</h2><div className="admin-toolbar"><label>Perioada<select value={days} onChange={e=>{setLoading(true);setError('');setDays(e.target.value);}}>{[7,30,90].map(n=><option key={n} value={n}>Ultimele {n} zile</option>)}</select></label><button className="secondary" onClick={()=>{setLoading(true);setError('');setRefresh(x=>x+1);}} disabled={loading}>Actualizează statistici</button></div>{error&&<p role="alert" className="admin-error">{error}</p>}{loading&&<p role="status">Se încarcă statisticile…</p>}{!loading&&data&&<><p>{data.installedAt?`Colectarea a început la ${new Date(data.installedAt).toLocaleString('ro-RO')}.`:'Nu există încă vizite măsurate. Colectarea începe cu prima vizită acceptată.'} Zilele sunt calculate în UTC.</p><div className="admin-summary"><article className="admin-card"><span>Vizualizări de pagini</span><strong>{data.pageviews}</strong></article><article className="admin-card"><span>Vizitatori-zile estimați</span><strong>{data.dailyUniqueSum}</strong></article>{Object.entries(labels).filter(([k])=>k!=='pageview').map(([k,label])=><article className="admin-card" key={k}><span>{label}</span><strong>{data.events[k]||0}</strong></article>)}</div><div className="analytics-columns">{(['pages','sources','devices'] as const).map(field=><div key={field}><h3>{{pages:'Pagini populare',sources:'Surse de trafic',devices:'Dispozitive'}[field]}</h3>{Object.entries(data[field]).sort((a,b)=>b[1]-a[1]).map(([label,n])=><p className="admin-deadline" key={label}><span>{label}</span><strong>{n}</strong></p>)}{!Object.keys(data[field]).length&&<p>Nicio vizualizare măsurată.</p>}</div>)}</div><h3>Evoluție zilnică</h3><div className="analytics-table"><table><thead><tr><th>Zi UTC</th><th>Vizualizări</th><th>Vizitatori estimați</th></tr></thead><tbody>{data.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.pageviews}<div className="analytics-bar" style={{width:`${d.pageviews/Math.max(1,...data.daily.map(x=>x.pageviews))*100}%`}}/></td><td>{d.unique}</td></tr>)}</tbody></table></div></>}
 <details><summary>Definiții, confidențialitate și limite</summary><p>Vizualizare = încărcare măsurată a unei pagini publice; reîncărcarea contează din nou. Adminul este exclus. JavaScript, blocatoarele, erorile de rețea, Do Not Track și Global Privacy Control pot reduce numărătoarea. Roboții cunoscuți sunt excluși; filtrarea nu este perfectă.</p><p>Vizitator zilnic estimat = combinație de IP și browser transformată pe server într-un identificator HMAC diferit în fiecare zi. IP-ul și browserul brut nu sunt salvate. Rețelele comune pot uni vizitatori; schimbările de IP/browser îi pot separa. Totalul perioadei este suma vizitatorilor zilnici, nu numărul de persoane distincte în întreaga perioadă.</p><p>Sursele reprezintă categoria referrer-ului pentru fiecare vizualizare, fără URL-uri complete, query-uri sau identificatori de campanie. Direct / necunoscut include referrer ascuns. Dispozitivele sunt clasificate aproximativ din browser. Nu folosim cookie-uri sau localStorage pentru măsurare. Datele sunt păstrate maximum 90 de zile, cu curățare zilnică.</p><p>Clicurile măsoară apăsări pe linkuri, nu conversații sau clienți. Inițiere checkout = încercare în browser de creare a unei comenzi; poate eșua și nu dovedește o plată. Aceste statistici nu raportează conversii sau încasări PayPal. Nu există date istorice înainte de instalare.</p></details></section>;
}
