"use client";
import {useState,useRef} from 'react';
import type {MapConnection} from './traffic-map';
const project=(lat:number,lon:number,z:number)=>{const scale=256*2**z,s=Math.sin(Math.max(-85.051,Math.min(85.051,lat))*Math.PI/180);return {x:(lon+180)/360*scale,y:(0.5-Math.log((1+s)/(1-s))/(4*Math.PI))*scale};};
export function DetailedMap({connections}:{connections:MapConnection[]}){
 const [zoom,setZoom]=useState(8),[center,setCenter]=useState({lat:47.05,lon:28.85}),[active,setActive]=useState<MapConnection|null>(null);
 const drag=useRef<{x:number;y:number;cx:number;cy:number}|null>(null);
 const c=project(center.lat,center.lon,zoom),width=768,height=480,n=2**zoom,tiles=[];
 for(let x=Math.floor((c.x-width/2)/256);x<=Math.floor((c.x+width/2)/256);x++)for(let y=Math.floor((c.y-height/2)/256);y<=Math.floor((c.y+height/2)/256);y++)if(y>=0&&y<n)tiles.push({x,y});
 function move(x:number,y:number){setCenter({lon:x/(256*n)*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/(256*n))))*180/Math.PI});}
 return <section><h4>Hartă detaliată · Moldova</h4><p>Zoomul schimbă detaliile hărții, nu precizia localizării vizitatorului. Punctele IP rămân aproximative, rotunjite la 0,1°.</p><div className="admin-actions"><button type="button" disabled={zoom>=18} onClick={()=>setZoom(zoom+1)}>Zoom +</button><button type="button" disabled={zoom<=2} onClick={()=>setZoom(zoom-1)}>Zoom −</button><button type="button" onClick={()=>{setCenter({lat:47.05,lon:28.85});setZoom(8);}}>Moldova</button></div><svg viewBox="0 0 768 480" style={{width:'100%',background:'#e2e8f0',touchAction:'none',cursor:'grab'}} role="group" aria-label="Hartă detaliată OpenStreetMap; glisează sau folosește săgețile pentru deplasare" tabIndex={0} onKeyDown={e=>{const shifts:Record<string,[number,number]>={ArrowLeft:[-128,0],ArrowRight:[128,0],ArrowUp:[0,-128],ArrowDown:[0,128]};if(shifts[e.key]){e.preventDefault();move(c.x+shifts[e.key][0],c.y+shifts[e.key][1]);}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,cx:c.x,cy:c.y};}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onPointerMove={e=>{if(drag.current){const scale=width/e.currentTarget.getBoundingClientRect().width;move(drag.current.cx-(e.clientX-drag.current.x)*scale,drag.current.cy-(e.clientY-drag.current.y)*scale);}}}>
 {tiles.map(t=><image key={t.x+','+t.y} href={`https://tile.openstreetmap.org/${zoom}/${((t.x%n)+n)%n}/${t.y}.png`} x={t.x*256-c.x+width/2} y={t.y*256-c.y+height/2} width={256} height={256}/>)}
 {connections.filter(p=>typeof p.latitude==='number'&&typeof p.longitude==='number').map(p=>{const point=project(p.latitude!,p.longitude!,zoom);return <g key={p.ip} tabIndex={0} role="button" aria-label={p.city+' · zonă IP aproximativă'} onClick={()=>setActive(p)} onKeyDown={e=>{if(e.key==='Enter')setActive(p);}}><circle cx={point.x-c.x+width/2} cy={point.y-c.y+height/2} r={12} fill="#0f766e" fillOpacity={0.6} stroke="white"/><title>{p.city} · aproximativ</title></g>;})}</svg><small>© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>. Tiles externe: furnizorul vede cererile administratorului, fără IP-urile vizitatorilor sau datele review-urilor.</small>{active&&<p>{active.city} · {active.country} · zonă IP aproximativă {active.latitude?.toFixed(1)}°, {active.longitude?.toFixed(1)}° · {active.pageviews} vizualizări</p>}</section>;
}
