'use client';
import { ReviewInvitations } from './review-invitations';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
type Review={id:string;key:string;etag:string;name:string;project:string;message:string;website:string;rating:number;status:string;published:boolean;createdAt:string;source:string};
export function ReviewsPanel({csrf}:{csrf:string}){
 const [items,setItems]=useState<Review[]>([]),[editing,setEditing]=useState<Review|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/admin?action=reviews',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.message);setItems(d.reviews);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function save(item:Review,remove=false){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin?action=review-save',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({key:item.key,etag:item.etag,remove,record:{...item,clientWebsite:item.website}})});const d=await r.json();if(!r.ok)throw Error(d.message);await load();setEditing(null);setNotice(remove?'Review șters.':'Review actualizat.');}catch(e){setError(e instanceof Error?e.message:'Eroare.');}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(editing)await save(editing);}
 return <section><h2>Review-uri</h2><p>Testimonialele existente au fost importate din homepage. Review-urile vechi din formular sunt păstrate și așteaptă verificarea; cele noi necesită aprobare. Numai cele aprobate și publicate apar pe site. Aprobarea nu certifică identitatea autorului.</p><ReviewInvitations csrf={csrf}/><section className="admin-card"><h3>Exemple demonstrative — nu sunt review-uri reale</h3><p>Septembrie 2026 este o perioadă ilustrativă; aceste texte nu provin de la clienți și nu intră în rating sau în lista publică.</p><p><strong>Exemplu demonstrativ 1 · septembrie 2026</strong>: Comunicarea a fost clară, iar structura propusă a făcut serviciile mai ușor de înțeles. Ajustările de design au fost explicate pe parcurs.</p><p><strong>Exemplu demonstrativ 2 · septembrie 2026</strong>: Varianta pentru telefon este simplu de folosit. Informațiile de contact sunt vizibile, iar paginile prezintă oferta într-un mod ordonat.</p></section><div className="admin-toolbar"><label>Filtrează<select aria-label="Filtrează" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toate</option><option value="pending">În așteptare</option><option value="approved">Aprobate</option><option value="rejected">Respinse</option><option value="published">Publicate</option><option value="hidden">Ascunse</option></select></label><button className="secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Reîncarcă review-uri</button><button className="secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='reviews-backup.json';a.click();URL.revokeObjectURL(url);}}>Export review-uri</button></div>
 {error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
 {editing&&<form className="admin-card admin-form" onSubmit={submit}><h3>Editează review</h3>{(['name','project','website'] as const).map(key=><label key={key}>{({name:'Nume',project:'Proiect',website:'Website'})[key]}<input required={key==='name'} type={key==='website'?'url':'text'} maxLength={key==='name'?80:key==='project'?100:180} value={editing[key]||''} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></label>)}<label>Review<textarea aria-label="Review" required minLength={12} maxLength={900} value={editing.message} onChange={e=>setEditing({...editing,message:e.target.value})}/></label><label>Stele<select aria-label="Stele" value={editing.rating} onChange={e=>setEditing({...editing,rating:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Moderare<select aria-label="Moderare" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value,published:e.target.value==='approved'?editing.published:false})}><option value="pending">În așteptare</option><option value="approved">Aprobat</option><option value="rejected">Respins</option></select></label><label><input type="checkbox" disabled={editing.status!=='approved'} checked={editing.published} onChange={e=>setEditing({...editing,published:e.target.checked})}/> Publicat pe site</label><div className="admin-actions"><button disabled={busy}>Salvează review</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Anulează</button></div></form>}
 <div className="admin-list">{items.filter(r=>filter==='all'||filter==='published'&&r.published||filter==='hidden'&&!r.published||r.status===filter).map(r=><article className="admin-card" key={r.key}><h3>{r.name} · {r.rating}/5</h3><p>{r.project}</p><p className="admin-notes">{r.message}</p><p>{r.createdAt?new Date(r.createdAt).toLocaleDateString('ro-RO'):'Dată necunoscută'} · {r.source==='existing-homepage'?'Testimonial homepage existent':'Formular client'}</p><span className="admin-badge">{r.status==='pending'?'În așteptare':r.status==='approved'?'Aprobat':'Respins'} · {r.published?'Publicat':'Ascuns'}</span><div className="admin-actions"><button disabled={busy} className="secondary" onClick={()=>setEditing(r)}>Editează review</button><button disabled={busy} onClick={()=>save({...r,status:'approved',published:true})}>Aprobă și publică</button><button disabled={busy} className="secondary" onClick={()=>save({...r,status:'rejected',published:false})}>Respinge</button>{r.status==='approved'&&<button disabled={busy} className="secondary" onClick={()=>save({...r,published:!r.published})}>{r.published?'Ascunde':'Publică'}</button>}<button disabled={busy} className="danger" onClick={()=>{if(confirm('Ștergi definitiv acest review?'))void save(r,true);}}>Șterge review</button></div></article>)}</div>{!items.length&&<p>Niciun review încărcat.</p>}</section>;
}
