"use client";
import {useCallback,useEffect,useState,type FormEvent} from 'react';
type Invitation={key:string;client:string;expiresAt:number;usedAt?:string;revoked?:boolean};
export function ReviewInvitations({csrf}:{csrf:string}){
 const [items,setItems]=useState<Invitation[]>([]),[client,setClient]=useState(''),[days,setDays]=useState(7),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/api/admin?action=invitations',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.message);setItems(d.invitations);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function mutate(action:string,body:object){const r=await fetch('/api/admin?action='+action,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message);return d;}
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await mutate('invitation-create',{client,days});setLink(location.origin+'/feedback#invitation='+d.token);await load();}catch(e){setError(e instanceof Error?e.message:'Eroare');}finally{setBusy(false);}}
 return <section className="admin-card"><h3>Invitații individuale pentru review</h3><p>Trimite personal linkul clientului. Expiră și acceptă o singură trimitere. Review-ul rămâne ascuns până la aprobare. Linkul secret este afișat numai la creare.</p><form onSubmit={create} className="admin-form"><label>Client invitat<input required minLength={2} maxLength={100} value={client} onChange={e=>setClient(e.target.value)}/></label><label>Expiră în zile<input type="number" min={1} max={30} required value={days} onChange={e=>setDays(Number(e.target.value))}/></label><button disabled={busy}>Creează invitație</button></form>{link&&<label>Link individual<input readOnly value={link} onFocus={e=>e.target.select()}/></label>}{error&&<p role="alert">{error}</p>}<div className="admin-list">{items.map(i=><article key={i.key}><strong>{i.client}</strong> · {i.revoked?'Revocată':i.usedAt?'Utilizată':i.expiresAt<=Date.now()?'Expirată':'Activă'} · {new Date(i.expiresAt).toLocaleString('ro-RO')}{!i.revoked&&!i.usedAt&&<button type="button" className="secondary" onClick={()=>{mutate('invitation-revoke',{key:i.key}).then(load).catch(e=>setError(e.message));}}>Revocă invitația</button>}</article>)}</div></section>;
}
